/**
 * Created by zhangmaliang on 2017/7/19.
 */

// APP公共相关
export const APP_SETUPDATA = 'APP_SETUPDATA';


// 登录相关
export const LOGIN_LOGIN = 'LOGIN_LOGIN';
export const LOGIN_PHONE_PWD_DIDCHANGED = 'LOGIN_PHONE_PWD_DIDCHANGED';
export const LOGIN_SENDVERTIFYCODE = 'LOGIN_SENDVERTIFYCODE';


// 导入联系人页面
export const CONTACT_LOADDATA = 'CONTACT_LOADDATA';
export const CONTACT_ITEMCLICKED = 'CONTACT_ITEMCLICKED';
export const CONTACT_SUREBTNCLICKED = 'CONTACT_SUREBTNCLICKED';
export const CONTACT_CANCELORSELECTALL = 'CONTACT_CANCELORSELECTALL';

// 会议人员选择页面
export const CONFERENCE_LOADDATA = 'CONFERENCE_LOADDATA';
export const CONFERENCE_ITEMCLICKED = 'CONFERENCE_ITEMCLICKED';
export const CONFERENCE_MOBILELICKED = 'CONFERENCE_MOBILELICKED';


// 会议列表页面
export const CONFERENCE_LIST_LOADDATA_SUCCESS = 'CONFERENCE_LIST_LOADDATA_SUCCESS';
export const CONFERENCE_LIST_LOADDATA_ERROR = 'CONFERENCE_LIST_LOADDATA_ERROR';
export const CONFERENCE_LIST_LOADDATA_REFRESH = 'CONFERENCE_LIST_LOADDATA_REFRESH';
export const CONFERENCE_LIST_LOADDATA_LOADMORE = 'CONFERENCE_LIST_LOADDATA_LOADMORE';
export const CONFERENCE_LIST_PERMISSION = 'CONFERENCE_LIST_PERMISSION';
export const CONFERENCE_LIST_DELETEITEM = 'CONFERENCE_LIST_DELETEITEM';


/*
*   注意，不能使用公共的key，必须保证一对一关系。 因为Action和Reducer就只靠这个做为联系
*   比如，若两个Action的方法里面都返回了同一个key，则响应的Reducer会混乱，出错
*
* */